// Standalone Mock Data Layer for Pure Frontend UI Mode

export const mockUsers = {
  'admin@spiceavenue.com': {
    userId: 1,
    fullName: 'System Admin',
    email: 'admin@spiceavenue.com',
    role: 'ADMIN',
    token: 'mock-jwt-admin-token',
  },
  'ops@spiceavenue.com': {
    userId: 2,
    fullName: 'Operations Manager',
    email: 'ops@spiceavenue.com',
    role: 'OPS_MANAGER',
    token: 'mock-jwt-ops-token',
  },
  'manager.colombo@spiceavenue.com': {
    userId: 3,
    fullName: 'Kasun Perera',
    email: 'manager.colombo@spiceavenue.com',
    role: 'BRANCH_MANAGER',
    token: 'mock-jwt-colombo-manager-token',
    branchId: 1,
  },
  'manager.negombo@spiceavenue.com': {
    userId: 4,
    fullName: 'Dinesh Silva',
    email: 'manager.negombo@spiceavenue.com',
    role: 'BRANCH_MANAGER',
    token: 'mock-jwt-negombo-manager-token',
    branchId: 2,
  },
  'rider.kamal@spiceavenue.com': {
    userId: 5,
    fullName: 'Kamal Fernando',
    email: 'rider.kamal@spiceavenue.com',
    role: 'RIDER',
    riderStatus: 'AVAILABLE',
    token: 'mock-jwt-rider-token',
  },
  'rider.nimal@spiceavenue.com': {
    userId: 6,
    fullName: 'Nimal Bandara',
    email: 'rider.nimal@spiceavenue.com',
    role: 'RIDER',
    riderStatus: 'BUSY',
    token: 'mock-jwt-rider2-token',
  },
  'supervisor@spiceavenue.com': {
    userId: 7,
    fullName: 'Sarah Jayasinghe',
    email: 'supervisor@spiceavenue.com',
    role: 'SUPERVISOR',
    token: 'mock-jwt-supervisor-token',
  },
  'customer.john@gmail.com': {
    userId: 8,
    fullName: 'John Doe',
    email: 'customer.john@gmail.com',
    role: 'CUSTOMER',
    token: 'mock-jwt-customer-token',
  },
};

export const mockBranches = [
  {
    branchId: 1,
    branchName: 'Spice Avenue - Colombo Main',
    streetAddress: '123 Galle Road, Colombo 03',
    contactNumber: '0112345678',
    email: 'colombo@spiceavenue.com',
    openingTime: '09:00:00',
    closingTime: '23:00:00',
    status: 'ACTIVE',
    managerName: 'Kasun Perera',
    managerEmail: 'manager.colombo@spiceavenue.com',
    managerId: 3,
    deliveryAreas: [
      { areaId: 1, areaName: 'Colombo 03 (Kollupitiya)', deliveryFee: 150.0, status: 'ACTIVE' },
      { areaId: 2, areaName: 'Colombo 07 (Cinnamon Gardens)', deliveryFee: 200.0, status: 'ACTIVE' },
      { areaId: 3, areaName: 'Colombo 04 (Bambalapitiya)', deliveryFee: 180.0, status: 'ACTIVE' },
    ],
  },
  {
    branchId: 2,
    branchName: 'Spice Avenue - Negombo Coastal',
    streetAddress: '45 Lewis Place, Negombo',
    contactNumber: '0312233445',
    email: 'negombo@spiceavenue.com',
    openingTime: '10:00:00',
    closingTime: '22:30:00',
    status: 'ACTIVE',
    managerName: 'Dinesh Silva',
    managerEmail: 'manager.negombo@spiceavenue.com',
    managerId: 4,
    deliveryAreas: [
      { areaId: 4, areaName: 'Negombo Town', deliveryFee: 120.0, status: 'ACTIVE' },
      { areaId: 5, areaName: 'Kochchikade', deliveryFee: 250.0, status: 'ACTIVE' },
    ],
  },
  {
    branchId: 3,
    branchName: 'Spice Avenue - Kandy Express',
    streetAddress: '88 Dalada Veediya, Kandy',
    contactNumber: '0812223344',
    email: 'kandy@spiceavenue.com',
    openingTime: '08:30:00',
    closingTime: '21:30:00',
    status: 'INACTIVE',
    managerName: 'Unassigned',
    managerEmail: null,
    managerId: null,
    deliveryAreas: [
      { areaId: 6, areaName: 'Kandy City Center', deliveryFee: 150.0, status: 'ACTIVE' },
    ],
  },
];

export const mockCategories = [
  { categoryId: 1, categoryName: 'Signature Pizzas', description: 'Woodfired thin crust pizzas', status: 'ACTIVE' },
  { categoryId: 2, categoryName: 'Gourmet Burgers', description: 'Handcrafted beef & chicken burgers', status: 'ACTIVE' },
  { categoryId: 3, categoryName: 'Rice & Biryani', description: 'Authentic aromatic rice dishes', status: 'ACTIVE' },
  { categoryId: 4, categoryName: 'Refreshing Drinks', description: 'Chilled beverages and mocktails', status: 'ACTIVE' },
];

export const mockMenuItems = [
  {
    itemId: 101,
    foodName: 'Spicy Chicken BBQ Pizza',
    description: 'Grilled chicken, fresh bell peppers, onions & mozzarella drizzled with smoky BBQ sauce',
    basePrice: 1850.0,
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&auto=format&fit=crop&q=60',
    isAvailable: true,
    status: 'ACTIVE',
    categoryId: 1,
    categoryName: 'Signature Pizzas',
    variations: [
      { variationId: 201, variationName: 'Personal (8")', additionalPrice: 0.0, status: 'ACTIVE' },
      { variationId: 202, variationName: 'Medium (12")', additionalPrice: 650.0, status: 'ACTIVE' },
      { variationId: 203, variationName: 'Large (16")', additionalPrice: 1200.0, status: 'ACTIVE' },
    ],
  },
  {
    itemId: 102,
    foodName: 'Double Cheese Beef Smash Burger',
    description: 'Two juicy beef smash patties, double cheddar cheese, caramelized onions & house special sauce',
    basePrice: 1450.0,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60',
    isAvailable: true,
    status: 'ACTIVE',
    categoryId: 2,
    categoryName: 'Gourmet Burgers',
    variations: [
      { variationId: 204, variationName: 'Single Patty', additionalPrice: 0.0, status: 'ACTIVE' },
      { variationId: 205, variationName: 'Double Patty + Fries', additionalPrice: 400.0, status: 'ACTIVE' },
    ],
  },
  {
    itemId: 103,
    foodName: 'Hyderabadi Chicken Dum Biryani',
    description: 'Slow-cooked marinated chicken layered with basmati rice, served with raita and gravy',
    basePrice: 1350.0,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=60',
    isAvailable: true,
    status: 'ACTIVE',
    categoryId: 3,
    categoryName: 'Rice & Biryani',
    variations: [
      { variationId: 206, variationName: 'Regular Portion', additionalPrice: 0.0, status: 'ACTIVE' },
      { variationId: 207, variationName: 'Family Pack (Serves 3)', additionalPrice: 1800.0, status: 'ACTIVE' },
    ],
  },
  {
    itemId: 104,
    foodName: 'Iced Passionfruit Mint Mojito',
    description: 'Fresh passionfruit pulp, lime juice, fresh mint leaves & sparkling soda',
    basePrice: 480.0,
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60',
    isAvailable: false,
    status: 'ACTIVE',
    categoryId: 4,
    categoryName: 'Refreshing Drinks',
    variations: [],
  },
];

export const mockOrders = [
  {
    orderId: 1001,
    orderNumber: 'ORD-20260915-001',
    customerName: 'John Doe',
    customerPhone: '0771234567',
    orderType: 'DELIVERY',
    status: 'DELIVERED',
    branchName: 'Spice Avenue - Colombo Main',
    subtotal: 2500.0,
    deliveryFee: 150.0,
    totalAmount: 2650.0,
    paymentMethod: 'CARD',
    estimatedPrepMinutes: 25,
    deliveryAddressText: 'House 24, Galle Road, Colombo 03',
    createdAt: '2026-09-15T19:15:00',
    items: [
      { orderItemId: 1, itemName: 'Spicy Chicken BBQ Pizza', variationName: 'Medium (12")', quantity: 1, unitPrice: 2500.0, totalPrice: 2500.0 },
    ],
  },
  {
    orderId: 1004,
    orderNumber: 'ORD-20260915-004',
    customerName: 'Kavinda Jayasuriya',
    customerPhone: '0778899000',
    orderType: 'DELIVERY',
    status: 'PENDING',
    subtotal: 2800.0,
    deliveryFee: 200.0,
    totalAmount: 3000.0,
    paymentMethod: 'CARD',
    deliveryAddressText: 'No 42, Havelock Road, Colombo 05',
    createdAt: '2026-09-15T19:35:00',
    items: [
      { orderItemId: 4, itemName: 'Spicy Chicken BBQ Pizza', variationName: 'Large (16")', quantity: 1, unitPrice: 3050.0, totalPrice: 3050.0 },
      { orderItemId: 5, itemName: 'Lime & Mint Sparkler', variationName: null, quantity: 2, unitPrice: 450.0, totalPrice: 900.0 },
    ],
  },
  {
    orderId: 1005,
    orderNumber: 'ORD-20260915-005',
    customerName: 'Dilani Wickramasinghe',
    customerPhone: '0761122334',
    orderType: 'PICKUP',
    status: 'PENDING',
    subtotal: 1450.0,
    deliveryFee: 0.0,
    totalAmount: 1450.0,
    paymentMethod: 'CASH_ON_DELIVERY',
    createdAt: '2026-09-15T19:40:00',
    items: [
      { orderItemId: 6, itemName: 'Double Cheese Beef Smash Burger', variationName: 'Single Patty', quantity: 1, unitPrice: 1450.0, totalPrice: 1450.0 },
    ],
  },
  {
    orderId: 1002,
    orderNumber: 'ORD-20260915-002',
    customerName: 'Saman Kumara',
    customerPhone: '0719876543',
    orderType: 'DELIVERY',
    status: 'READY_FOR_DELIVERY',
    subtotal: 1850.0,
    deliveryFee: 200.0,
    totalAmount: 2050.0,
    paymentMethod: 'CASH_ON_DELIVERY',
    estimatedPrepMinutes: 20,
    deliveryAddressText: 'No 15, Cinnamon Gardens, Colombo 07',
    createdAt: '2026-09-15T19:00:00',
    items: [
      { orderItemId: 2, itemName: 'Double Cheese Beef Smash Burger', variationName: 'Double Patty + Fries', quantity: 1, unitPrice: 1850.0, totalPrice: 1850.0 },
    ],
  },
  {
    orderId: 1003,
    orderNumber: 'ORD-20260915-003',
    customerName: 'Amali Perera',
    customerPhone: '0754443322',
    orderType: 'PICKUP',
    status: 'PREPARING',
    subtotal: 1350.0,
    deliveryFee: 0.0,
    totalAmount: 1350.0,
    paymentMethod: 'CARD',
    estimatedPrepMinutes: 15,
    createdAt: '2026-09-15T19:25:00',
    items: [
      { orderItemId: 3, itemName: 'Hyderabadi Chicken Dum Biryani', variationName: 'Regular Portion', quantity: 1, unitPrice: 1350.0, totalPrice: 1350.0 },
    ],
  },
];

export const mockRiderTasks = [
  {
    deliveryId: 501,
    orderId: 1002,
    orderNumber: 'ORD-20260915-002',
    customerName: 'Saman Kumara',
    customerPhone: '0719876543',
    deliveryAddress: 'No 15, Cinnamon Gardens, Colombo 07',
    branchName: 'Spice Avenue - Colombo Main',
    status: 'ASSIGNED',
    totalAmount: 2050.0,
    paymentMethod: 'CASH_ON_DELIVERY',
    assignedAt: '2026-09-15T19:20:00',
  },
];

export const mockRiderHistory = [
  {
    deliveryId: 499,
    orderNumber: 'ORD-20260914-088',
    customerName: 'Ruwan Silva',
    deliveryAddress: 'Colombo 04',
    status: 'DELIVERED',
    deliveredAt: '2026-09-14T20:45:00',
    totalAmount: 1950.0,
  },
];

export const mockComplaints = [
  {
    complaintId: 1,
    orderId: 1001,
    orderNumber: 'ORD-20260915-001',
    customerName: 'John Doe',
    customerPhone: '0771234567',
    category: 'Wrong Food Delivered',
    description: 'I ordered BBQ Chicken pizza but received Veggie Delight instead.',
    status: 'PENDING',
    createdAt: '2026-09-15T19:30:00',
  },
  {
    complaintId: 2,
    orderId: 988,
    orderNumber: 'ORD-20260914-045',
    customerName: 'Kavindi Fernando',
    customerPhone: '0723334455',
    category: 'Late Delivery',
    description: 'Food arrived 45 minutes past estimated preparation time.',
    status: 'RESOLVED',
    resolutionNotes: 'Apologized to customer and issued a 20% discount coupon for next purchase.',
    createdAt: '2026-09-14T21:10:00',
  },
];

export const mockReviews = [
  {
    reviewId: 1,
    orderNumber: 'ORD-20260915-001',
    customerName: 'John Doe',
    rating: 5,
    comment: 'Delicious woodfired pizza! Very quick delivery.',
    reviewDate: '2026-09-15T19:35:00',
  },
  {
    reviewId: 2,
    orderNumber: 'ORD-20260914-099',
    customerName: 'Nipuni Wickrama',
    rating: 4,
    comment: 'Smash burgers were juicy. Will order again.',
    reviewDate: '2026-09-14T18:20:00',
  },
];

export const mockUsersList = [
  { userId: 1, fullName: 'System Admin', email: 'admin@spiceavenue.com', role: 'ADMIN', status: 'ACTIVE', branchName: 'All Branches', createdAt: '2026-01-10' },
  { userId: 2, fullName: 'Operations Manager', email: 'ops@spiceavenue.com', role: 'OPS_MANAGER', status: 'ACTIVE', branchName: 'All Branches', createdAt: '2026-01-12' },
  { userId: 3, fullName: 'Kasun Perera', email: 'manager.colombo@spiceavenue.com', role: 'BRANCH_MANAGER', status: 'ACTIVE', branchName: 'Colombo Main', createdAt: '2026-02-01' },
  { userId: 4, fullName: 'Dinesh Silva', email: 'manager.negombo@spiceavenue.com', role: 'BRANCH_MANAGER', status: 'ACTIVE', branchName: 'Negombo Coastal', createdAt: '2026-02-05' },
  { userId: 9, fullName: 'Nuwan Fernando', email: 'manager.kandy@spiceavenue.com', role: 'BRANCH_MANAGER', status: 'ACTIVE', branchName: 'Unassigned', createdAt: '2026-02-08' },
  { userId: 10, fullName: 'Priyantha Bandara', email: 'manager.galle@spiceavenue.com', role: 'BRANCH_MANAGER', status: 'ACTIVE', branchName: 'Unassigned', createdAt: '2026-02-12' },
  { userId: 5, fullName: 'Kamal Fernando', email: 'rider.kamal@spiceavenue.com', role: 'RIDER', status: 'ACTIVE', branchName: 'Colombo Main', createdAt: '2026-02-10' },
  { userId: 6, fullName: 'Nimal Bandara', email: 'rider.nimal@spiceavenue.com', role: 'RIDER', status: 'ACTIVE', branchName: 'Colombo Main', createdAt: '2026-02-12' },
  { userId: 7, fullName: 'Sarah Jayasinghe', email: 'supervisor@spiceavenue.com', role: 'SUPERVISOR', status: 'ACTIVE', branchName: 'Customer Support HQ', createdAt: '2026-02-15' },
  { userId: 8, fullName: 'John Doe', email: 'customer.john@gmail.com', role: 'CUSTOMER', status: 'ACTIVE', branchName: 'External', createdAt: '2026-03-01' },
];

export const mockAuditLogs = [
  { logId: 101, timestamp: '2026-09-15 19:45:12', userEmail: 'admin@spiceavenue.com', role: 'ADMIN', eventType: 'USER_ROLE_UPDATE', details: 'Updated user Dinesh Silva role to BRANCH_MANAGER', ipAddress: '192.168.1.10' },
  { logId: 102, timestamp: '2026-09-15 19:20:05', userEmail: 'ops@spiceavenue.com', role: 'OPS_MANAGER', eventType: 'BRANCH_CREATE', details: 'Created new branch: Spice Avenue - Kandy Express', ipAddress: '192.168.1.15' },
  { logId: 103, timestamp: '2026-09-15 18:55:40', userEmail: 'manager.colombo@spiceavenue.com', role: 'BRANCH_MANAGER', eventType: 'MENU_PRICE_CHANGE', details: 'Updated Spicy BBQ Pizza price to Rs.1850', ipAddress: '192.168.1.22' },
  { logId: 104, timestamp: '2026-09-15 18:10:19', userEmail: 'supervisor@spiceavenue.com', role: 'SUPERVISOR', eventType: 'COMPLAINT_RESOLVE', details: 'Resolved complaint #1001 for customer John Doe', ipAddress: '192.168.1.30' },
  { logId: 105, timestamp: '2026-09-15 17:30:00', userEmail: 'rider.kamal@spiceavenue.com', role: 'RIDER', eventType: 'RIDER_STATUS_CHANGE', details: 'Status changed to AVAILABLE', ipAddress: '192.168.1.44' },
];

export const mockSystemSettings = {
  maintenanceMode: false,
  broadcastNotice: 'Welcome to Spice Avenue platform! All system services operating normally.',
  defaultOpeningTime: '08:00:00',
  defaultClosingTime: '23:00:00',
  currencySymbol: 'Rs.',
  maxActiveRiderOrders: 3,
  sessionTimeoutMinutes: 60,
  apiHealth: 'HEALTHY',
  dbHealth: 'HEALTHY',
  jwtServiceHealth: 'HEALTHY',
};

